(function(){
  const BUILD='v101';
  const C={green:'173F35',sage:'466964',gray:'DAD9D6',sand:'D6D2C4',orange:'DE7C00',cream:'F7F5EF',white:'FFFFFF',wine:'76232F',red:'E03C31',up:'157349',ink:'173F35',muted:'68736F'};
  let PERIOD='week', LAST=null, BUSY=false;
  const $id=id=>document.getElementById(id);
  const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fmtNum=v=>new Intl.NumberFormat('pt-BR').format(Math.round(Number(v)||0));
  const fmtPct=(v,d=2)=>Number.isFinite(Number(v))?(Number(v)*100).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d})+'%':'—';
  const fmtPp=v=>Number.isFinite(Number(v))?((Number(v)>0?'+':'')+(Number(v)*100).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+' p.p.'):'—';
  const fmtMoney=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(v)||0);
  const fmtMoneyK=v=>{v=Number(v)||0; return Math.abs(v)>=1000?'R$ '+(v/1000).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})+' mil':fmtMoney(v)};
  const periodName=p=>p==='month'?'Mês':p==='year'?'Ano':'Semana';
  const storeName=st=>{try{return typeof storeDisplayName==='function'?storeDisplayName(st):st}catch(e){return st}};
  const supStore=(st,n)=>{try{return typeof supervisorPrettyStoreV46==='function'?supervisorPrettyStoreV46(st,n):storeName(st)}catch(e){return storeName(st)}};
  const pref=(id,n)=>{try{return typeof preferredName==='function'?preferredName(id,n):(n||'')}catch(e){return n||''}};
  const supFirsts=store=>{try{const a=(store?.supervisors||[]).filter(u=>typeof supervisorEligibleRoleV49!=='function'||supervisorEligibleRoleV49(u.role)).map(u=>typeof supervisorFirstNameV48==='function'?supervisorFirstNameV48(u.id,u.name):(u.name||'').split(' ')[0]).filter(Boolean); return [...new Set(a)].join(' • ')||'Supervisores da loja'}catch(e){return 'Supervisores da loja'}};

  function status(msg,type=''){const el=$id('presStatusV101'); if(el)el.innerHTML='<div class="notice '+type+'">'+safe(msg)+'</div>'}
  window.adminPresentationV99=async function(){
    const asof=String(window.COMMON?.asof||new Date().toLocaleDateString('en-CA',{timeZone:'America/Fortaleza'}));
    const month=asof.slice(0,7); LAST=null;
    const w=$id('adminWork'); if(!w)return;
    w.innerHTML='<div class="card presAdmV99" style="gap:16px">'+
      '<div class=presHeroV99 style="min-height:160px;display:flex;flex-direction:column;justify-content:center;background:linear-gradient(135deg,#173F35,#466964);border-radius:24px;padding:22px;color:#fff;position:relative;overflow:hidden">'+
        '<div style="position:absolute;right:-65px;top:-70px;width:220px;height:220px;border-radius:50%;border:28px solid rgba(222,124,0,.25)"></div>'+ 
        '<h2 style="margin:0;font-size:26px;line-height:1.05">Apresentação eStore • CE+PI</h2>'+ 
        '<p style="margin:10px 0 0;color:#e8eeea;max-width:620px;font-size:13px;line-height:1.45">Gere uma apresentação executiva, alinhada ao padrão Riachuelo, com dados consolidados do App por semana, mês ou ano.</p>'+ 
      '</div>'+ 
      '<div class=presControlsV99 style="display:grid;grid-template-columns:1.2fr 1fr;gap:12px">'+
        '<div class=presChoiceV99><label>Período da apresentação</label><div class=presSegmentV99><button id=presWeekV101 class=on onclick="presSetPeriodV101(\'week\')">Semana</button><button id=presMonthBtnV101 onclick="presSetPeriodV101(\'month\')">Mês</button><button id=presYearV101 onclick="presSetPeriodV101(\'year\')">Ano</button></div><div id=presMonthBoxV101 style="display:none;margin-top:10px"><label>Mês de referência</label><input id=presMonthV101 type=month class=field value="'+safe(month)+'"></div></div>'+ 
        '<div class=presChoiceV99><label>Saída</label><div class=presActionsV99><button class="btn ghost" onclick="presPreviewV101()">Gerar prévia</button><button class=btn onclick="presGeneratePptxV99()">Gerar PowerPoint</button></div><div id=presStatusV101></div></div>'+ 
      '</div>'+ 
      '<div id=presPreviewV101 class=presPreviewV99>'+previewCards('week')+'</div>'+ 
    '</div>';
  };
  window.presSetPeriodV101=function(p){PERIOD=p; LAST=null; [['week','presWeekV101'],['month','presMonthBtnV101'],['year','presYearV101']].forEach(a=>$id(a[1])?.classList.toggle('on',a[0]===p)); const mb=$id('presMonthBoxV101'); if(mb)mb.style.display=p==='month'?'block':'none'; const pv=$id('presPreviewV101'); if(pv)pv.innerHTML=previewCards(p)};
  function previewCards(p){let arr=['Capa executiva com imagem','Resumo regional','Share: evolução e retração']; if(p==='week')arr.push('Lojas Priorizadas'); arr.push('Dispersões','Reconhecimento colaboradores','Pódio supervisores','Direcionamento final'); return arr.map((t,i)=>'<div class="presThumbV99 '+(i%3===1?'orange':i%3===2?'sage':'')+'"><b>'+String(i+1).padStart(2,'0')+' • '+safe(t)+'</b><small>'+periodName(p)+' • CE+PI • layout executivo final</small><div class=k><i>PowerPoint</i><i>Riachuelo</i></div></div>').join('')}

  async function loadData(){
    if(BUSY)throw new Error('A apresentação já está sendo gerada.'); BUSY=true;
    try{
      const month=PERIOD==='month'?($id('presMonthV101')?.value||String(window.COMMON?.asof||'2026-10-01').slice(0,7)):undefined;
      const calls=[api({action:'ranking_period',matricula:U.u.id,period:PERIOD,month,store:U.u.st}), api({action:'supervisor_highlights',matricula:U.u.id,period:PERIOD})];
      if(PERIOD==='week')calls.push(api({action:'fca_dashboard',matricula:U.u.id}));
      const [ranking,sup,fca]=await Promise.all(calls);
      const regional=(ranking.regional||[]).filter(x=>(+x.c||0)>0);
      const collabCaptured=[...regional].sort((a,b)=>(+b.c||0)-(+a.c||0)).slice(0,10);
      const collabOrders=[...regional].sort((a,b)=>(+b.o||0)-(+a.o||0)||(+b.c||0)-(+a.c||0)).slice(0,10);
      const supervisorRanking=[...(sup.sales||[])].sort((a,b)=>(+b.c||0)-(+a.c||0)).slice(0,10);
      const dispersion=[...(sup.stores||[])].filter(x=>(+x.total||0)>0).sort((a,b)=>(+b.disp||0)-(+a.disp||0)||(+b.zeros||0)-(+a.zeros||0)).slice(0,8);
      LAST={period:PERIOD,month,ranking,supervisors:sup,fca:fca||null,collabCaptured,collabOrders,supervisorRanking,dispersion,asof:sup.asof||COMMON?.asof||''}; return LAST;
    } finally {BUSY=false}
  }
  function summary(d){
    const stores=Array.isArray(d.supervisors?.stores)?d.supervisors.stores:[];
    const captured=stores.reduce((a,x)=>a+(+x.c||0),0), orders=stores.reduce((a,x)=>a+(+x.o||0),0), total=stores.reduce((a,x)=>a+(+x.total||0),0), zeros=stores.reduce((a,x)=>a+(+x.zeros||0),0);
    let share=Number(d.supervisors?.shareReference?.regionalShare); if(d.period==='week'&&d.fca?.summary?.share)share=+d.fca.summary.share; if(!Number.isFinite(share))share=0;
    return {share,captured:d.period==='week'&&d.fca?.summary?.captured?+d.fca.summary.captured:captured,orders:d.period==='week'&&d.fca?.summary?.orders?+d.fca.summary.orders:orders,ticket:orders?captured/orders:0,total,zeros,dispersion:total?zeros/total:0,share_delta:d.period==='week'?Number(d.fca?.summary?.share_delta):null};
  }
  function descriptor(d){if(d.period==='week')return 'Semana '+(d.fca?.weekNumber||'')+' vs Semana '+(d.fca?.previousWeekNumber||''); if(d.period==='month'){const x=new Date((d.month||'2026-10')+'-01T12:00:00'); return x.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}).replace(/^./,m=>m.toUpperCase())} return String((d.asof||COMMON?.asof||'2026').slice(0,4))}
  window.presPreviewV101=async function(){try{status('Consolidando dados...'); const d=await loadData(),s=summary(d); const pv=$id('presPreviewV101'); if(pv)pv.innerHTML='<div class=presThumbV99><b>Resumo • '+safe(descriptor(d))+'</b><small>Share '+fmtPct(s.share)+' • Captado '+fmtMoneyK(s.captured)+' • '+fmtNum(s.orders)+' pedidos • Ticket '+fmtMoney(s.ticket)+'</small></div><div class="presThumbV99 orange"><b>Reconhecimento</b><small>Top captado: '+safe(pref(d.collabCaptured[0]?.id,d.collabCaptured[0]?.name)||'—')+' • Top pedidos: '+safe(pref(d.collabOrders[0]?.id,d.collabOrders[0]?.name)||'—')+'</small></div>'+previewCards(d.period); status('Prévia atualizada.','success')}catch(e){status(e.message||'Erro na prévia.','danger')}};

  async function loadPptx(){if(window.pptxgen||window.PptxGenJS)return window.pptxgen||window.PptxGenJS; return new Promise((ok,err)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.bundle.js';s.onload=()=>ok(window.pptxgen||window.PptxGenJS);s.onerror=()=>err(new Error('Falha ao carregar o gerador PowerPoint.'));document.head.appendChild(s)})}
  async function dataUrl(url){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw 0;const b=await r.blob();return await new Promise((ok,er)=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.onerror=er;fr.readAsDataURL(b)})}catch(e){return ''}}
  async function logo(color){try{let r=await fetch('./assets/riachuelo-logo-exact-v75.svg?build='+BUILD,{cache:'no-store'});let svg=await r.text();svg=svg.replace(/fill="#fff"/gi,'fill="#'+color+'"').replace(/fill="#ffffff"/gi,'fill="#'+color+'"');return 'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(svg)))}catch(e){return ''}}
  async function coverPhoto(){const candidates=[]; try{['home_hero_1','home_hero_2','home_hero_3','community_cover'].forEach(id=>{const x=typeof appImageSlot==='function'?appImageSlot(id):null;if(x?.url&&String(x.media_type||'image')!=='video')candidates.push(x.url)})}catch(e){} candidates.push('./assets/campaign-share-v75.jpg'); for(const u of candidates){const d=await dataUrl(u); if(d)return d} return ''}
  function addText(slide,t,x,y,w,h,o={}){slide.addText(String(t??''),{x,y,w,h,fontFace:'Arial',fontSize:o.fs||12,bold:!!o.bold,color:o.color||C.green,align:o.align||'left',valign:o.valign||'mid',margin:o.margin===undefined?0:o.margin,fit:'shrink',breakLine:false,isTextBox:true})}
  function shape(slide,pptx,type,o){slide.addShape((pptx.ShapeType&&pptx.ShapeType[type])||type,o)}
  function header(slide,pptx,idx,title,sub,lg){addText(slide,String(idx).padStart(2,'0'),.32,.20,.32,.18,{fs:7,bold:true,color:C.orange,align:'center'});addText(slide,title,.72,.12,8.8,.35,{fs:18,bold:true});addText(slide,sub,.72,.47,8.8,.18,{fs:7.5,color:C.sage});if(lg)slide.addImage({data:lg,x:11.15,y:.18,w:1.55,h:.17});shape(slide,pptx,'line',{x:.72,y:.76,w:11.9,h:0,line:{color:C.sand,width:.8}})}
  function footer(slide){addText(slide,'MODA QUE INSPIRA O BRASIL',.58,7.18,3.2,.12,{fs:5.7,color:C.sage});addText(slide,'App. eStore CE+PI',11.2,7.16,1.4,.14,{fs:5.7,color:C.green,bold:true,align:'right'})}
  function card(slide,pptx,x,y,w,h,title,val,sub,accent=C.green,subc=C.muted){shape(slide,pptx,'roundRect',{x,y,w,h,rectRadius:.08,fill:{color:C.white},line:{color:'E5E1D8',width:.8},shadow:{type:'outer',color:'B9B3A7',opacity:.12,blur:1.2,angle:45,distance:1}});shape(slide,pptx,'ellipse',{x:x+.18,y:y+.18,w:.34,h:.34,fill:{color:accent},line:{color:accent}});addText(slide,title,x+.62,y+.16,w-.75,.23,{fs:7.3,bold:true});addText(slide,val,x+.20,y+.66,w-.40,.42,{fs:21,bold:true});addText(slide,sub,x+.20,y+1.16,w-.40,.25,{fs:6.3,bold:true,color:subc})}
  function rankTable(slide,pptx,title,rows,x,y,w,h,mode,start=1){shape(slide,pptx,'roundRect',{x,y,w,h,fill:{color:C.white},line:{color:'E5E1D8',width:.8}});shape(slide,pptx,'rect',{x,y,w,h:.43,fill:{color:C.green},line:{color:C.green}});addText(slide,title,x+.18,y+.07,w-.36,.24,{fs:9.5,bold:true,color:C.white});const rh=(h-.78)/Math.max(rows.length,1);const xName=x+.52,xV=x+w-2.12,x2=x+w-.75;['#',mode==='sup'?'Loja / Supervisores':'Nome / Loja',mode==='sup'?'Captado':'Captado',mode==='sup'?'Share':'Ped.'].forEach((t,i)=>addText(slide,t,[x+.16,xName,xV,x2][i],y+.50,[.24,w-2.95,1.25,.55][i],.16,{fs:5.1,bold:true,color:C.muted,align:i>1?'right':'left'}));rows.forEach((r,i)=>{const yy=y+.75+i*rh;if(i%2===0)shape(slide,pptx,'rect',{x:x+.08,y:yy,w:w-.16,h:rh-.02,fill:{color:'FBFAF7'},line:{color:'FBFAF7'}});addText(slide,String(start+i),x+.16,yy,.24,rh-.03,{fs:6.1,bold:true,color:C.orange});if(mode==='sup'){addText(slide,r.st+' • '+supStore(r.st,r.name),xName,yy,w-3.05,rh*.44,{fs:5.7,bold:true});addText(slide,supFirsts(r),xName,yy+rh*.43,w-3.05,rh*.35,{fs:4.6,color:C.muted});addText(slide,fmtMoneyK(r.c),xV,yy,1.25,rh-.03,{fs:5.7,bold:true,align:'right'});addText(slide,fmtPct(r.share),x2,yy,.55,rh-.03,{fs:5.7,bold:true,align:'right'})}else{addText(slide,pref(r.id,r.name),xName,yy,w-3.05,rh*.46,{fs:5.8,bold:true});addText(slide,'Filial '+r.st,xName,yy+rh*.45,w-3.05,rh*.35,{fs:4.7,color:C.muted});addText(slide,fmtMoneyK(r.c),xV,yy,1.25,rh-.03,{fs:5.7,bold:true,align:'right'});addText(slide,fmtNum(r.o),x2,yy,.55,rh-.03,{fs:5.7,bold:true,align:'right'})}})}
  function podium(slide,pptx,rows,title,valFn,x,y,w,h,mode){addText(slide,title,x,y,w,.28,{fs:11,bold:true,align:'center'});const order=[1,0,2],col=['C9CED1','D9A51D','C47B43'],by=[y+1.35,y+.86,y+1.53],bh=[1.12,1.62,.94];order.forEach((idx,j)=>{const r=rows[idx];if(!r)return;const bw=w/3-.12,bx=x+j*w/3+.06;shape(slide,pptx,'roundRect',{x:bx,y:by[j],w:bw,h:bh[j],fill:{color:col[j]},line:{color:col[j]}});addText(slide,(idx+1)+'º',bx,by[j]+.07,bw,.25,{fs:13,bold:true,color:j===1?C.white:C.green,align:'center'});const name=mode==='sup'?supFirsts(r):pref(r.id,r.name);addText(slide,name,bx+.10,by[j]+.41,bw-.20,.48,{fs:mode==='sup'?6.2:6.8,bold:true,color:j===1?C.white:C.green,align:'center'});addText(slide,mode==='sup'?(r.st+' • '+supStore(r.st,r.name)):('Filial '+r.st),bx+.10,by[j]+.88,bw-.20,.24,{fs:5.2,color:j===1?'FFF5D4':C.green,align:'center'});addText(slide,valFn(r),bx+.10,by[j]+bh[j]-.31,bw-.20,.21,{fs:6.7,bold:true,color:j===1?C.white:C.green,align:'center'})})}
  function barRows(slide,pptx,rows,x,y,w,h,key,label,color){const max=Math.max(...rows.map(r=>Math.abs(Number(r[key])||0)),.0001),rh=h/Math.max(rows.length,1);rows.forEach((r,i)=>{const yy=y+i*rh;addText(slide,label(r),x,yy,w*.40,rh-.03,{fs:5.8,bold:true});shape(slide,pptx,'roundRect',{x:x+w*.42,y:yy+.08,w:(w*.40)*Math.abs(+r[key]||0)/max,h:.16,fill:{color},line:{color}});addText(slide,key==='disp'?fmtPct(r[key],1):fmtPp(r[key]),x+w*.84,yy,w*.15,rh-.03,{fs:5.8,bold:true,color,align:'right'})})}

  async function buildDeck(d){const P=await loadPptx();const pptx=new P();pptx.layout='LAYOUT_WIDE';pptx.author='App. eStore CE+PI';pptx.company='Riachuelo';pptx.subject='Panorama Regional eStore CE+PI';pptx.title='Panorama Regional eStore • CE+PI';pptx.theme={headFontFace:'Arial',bodyFontFace:'Arial',lang:'pt-BR'};pptx.defineSlideMaster({title:'RCH',background:{color:C.cream},objects:[]});const lgW=await logo(C.white),lgG=await logo(C.green),photo=await coverPhoto(),s=summary(d),desc=descriptor(d);
    {const slide=pptx.addSlide();slide.background={color:C.green};if(photo)slide.addImage({data:photo,x:6.55,y:0,w:6.78,h:7.50,sizing:{type:'cover',x:6.55,y:0,w:6.78,h:7.50}});shape(slide,pptx,'rect',{x:6.55,y:0,w:6.78,h:7.50,fill:{color:'000000',transparency:60},line:{color:'000000',transparency:100}});shape(slide,pptx,'ellipse',{x:3.35,y:-1.28,w:5.95,h:9.70,fill:{color:C.green},line:{color:C.green}});shape(slide,pptx,'ellipse',{x:8.55,y:-2.10,w:6.25,h:10.05,fill:{color:C.orange,transparency:12},line:{color:C.orange,transparency:100}});shape(slide,pptx,'ellipse',{x:5.20,y:-1.08,w:4.50,h:8.90,fill:{color:C.green},line:{color:C.green}});if(lgW)slide.addImage({data:lgW,x:.66,y:.45,w:2.25,h:.18});shape(slide,pptx,'line',{x:.68,y:1.05,w:.48,h:0,line:{color:C.orange,width:2}});addText(slide,'PANORAMA\nREGIONAL',.68,1.30,5.35,1.35,{fs:35,bold:true,color:'E8E0D0'});addText(slide,'eStore • CE+PI',.68,2.72,4.7,.42,{fs:24,color:C.white});addText(slide,'Resultado '+periodName(d.period)+' | Share, Venda Captada, Pedidos e Ticket Médio',.70,3.34,5.40,.42,{fs:11,color:'E8ECEA'});addText(slide,desc,.70,3.92,3.8,.18,{fs:7.2,bold:true,color:'F2D398'});addText(slide,'MODA QUE INSPIRA O BRASIL',.70,6.82,3.3,.16,{fs:6.5,bold:true,color:'E6D8B8'});addText(slide,'01',12.55,.18,.34,.16,{fs:6.2,color:'F2D398',align:'right'});}
    {const slide=pptx.addSlide('RCH');header(slide,pptx,2,'RESUMO EXECUTIVO','eStore CE+PI | '+desc,lgG);[['Share eStore',fmtPct(s.share),Number.isFinite(s.share_delta)?fmtPp(s.share_delta):'Resultado regional',C.green,s.share_delta>=0?C.up:C.red],['Venda Captada',fmtMoneyK(s.captured),'Acumulado do período',C.orange,C.sage],['Pedidos',fmtNum(s.orders),'Volume do período',C.sand,C.sage],['Ticket Médio',fmtMoney(s.ticket),'Média regional',C.wine,C.sage]].forEach((a,i)=>card(slide,pptx,.55+i*3.18,1.05,2.92,1.58,a[0],a[1],a[2],a[3],a[4]));card(slide,pptx,.55,3.00,3.90,1.32,'Dispersão Regional',fmtPct(s.dispersion,1),fmtNum(s.zeros)+' colaboradores sem venda',C.orange,C.wine);card(slide,pptx,4.70,3.00,3.90,1.32,'Participação com venda',fmtPct(s.total?(s.total-s.zeros)/s.total:0,1),fmtNum(Math.max(0,s.total-s.zeros))+' de '+fmtNum(s.total)+' colaboradores',C.green,C.up);card(slide,pptx,8.85,3.00,3.90,1.32,'Lojas com venda',(d.supervisors?.stores||[]).filter(x=>(+x.c||0)>0).length+' / '+(d.supervisors?.stores||[]).length,'Regional CE+PI',C.sage,C.sage);addText(slide,'LEITURA EXECUTIVA',.62,4.75,2.2,.20,{fs:8,bold:true,color:C.orange});addText(slide,'O resultado consolida a performance regional do período, combinando entrega de Share, volume captado, pedidos, ticket médio e mobilização do time.',.62,5.10,11.6,.60,{fs:15,bold:true});footer(slide)}
    {const slide=pptx.addSlide('RCH');header(slide,pptx,3,d.period==='week'?'EVOLUÇÃO / RETRAÇÃO DE SHARE':'SHARE E PERFORMANCE POR LOJA',(d.period==='week'?'Comparativo semanal':'Leitura regional')+' | eStore CE+PI',lgG);card(slide,pptx,.55,1.06,2.80,1.58,'Share Regional',fmtPct(s.share),Number.isFinite(s.share_delta)?fmtPp(s.share_delta)+' vs semana anterior':'Resultado do período',C.green,s.share_delta>=0?C.up:C.red);if(d.period==='week'){barRows(slide,pptx,(d.fca?.growth||[]).slice(0,5),3.65,1.25,4.1,2.5,'share_delta',r=>r.st+' • '+storeName(r.st),C.up);addText(slide,'Maiores recuperações',3.65,.92,3.8,.22,{fs:12,bold:true});barRows(slide,pptx,(d.fca?.prioritized||[]).slice(0,5),8.10,1.25,4.1,2.5,'share_delta',r=>r.st+' • '+storeName(r.st),C.red);addText(slide,'Maiores retrações',8.10,.92,3.8,.22,{fs:12,bold:true,color:C.wine});card(slide,pptx,.55,4.30,3.75,1.22,'Lojas em evolução',fmtNum(d.fca?.summary?.evolved||0),'Share superior à semana anterior',C.up,C.up);card(slide,pptx,4.62,4.30,3.75,1.22,'Lojas estáveis',fmtNum(d.fca?.summary?.stable||0),'Sem variação relevante',C.sand,C.muted);card(slide,pptx,8.70,4.30,3.75,1.22,'Lojas em retração',fmtNum(d.fca?.summary?.retracted||0),'Share inferior à semana anterior',C.wine,C.red)}footer(slide)}
    if(d.period==='week'){const slide=pptx.addSlide('RCH');header(slide,pptx,4,'LOJAS PRIORIZADAS / FCA','Maiores retrações de Share | eStore CE+PI',lgG);const rows=(d.fca?.prioritized||[]).slice(0,5);shape(slide,pptx,'roundRect',{x:.50,y:1.07,w:12.25,h:4.95,fill:{color:C.white},line:{color:'E5E1D8',width:.8}});['#','Loja','Share ant.','Share atual','Δ p.p.','Captado','Ped.','Ticket','Dispersão'].forEach((t,i)=>addText(slide,t,[.63,.95,4.45,5.45,6.38,7.30,8.82,9.70,10.85][i],1.25,[.20,3.2,.75,.75,.70,1.10,.55,.82,1.05][i],.20,{fs:5.3,bold:true,color:C.muted,align:i>1?'right':'left'}));rows.forEach((r,i)=>{const yy=1.72+i*.76;if(i%2===0)shape(slide,pptx,'rect',{x:.56,y:yy-.04,w:12.10,h:.64,fill:{color:'FBFAF7'},line:{color:'FBFAF7'}});addText(slide,String(i+1),.63,yy,.20,.25,{fs:6,bold:true,color:C.orange});addText(slide,r.st+' • '+storeName(r.st),.95,yy,3.25,.25,{fs:6.1,bold:true});addText(slide,fmtPct(r.previous_share),4.45,yy,.75,.25,{fs:5.8,align:'right'});addText(slide,fmtPct(r.share),5.45,yy,.75,.25,{fs:5.8,bold:true,align:'right'});addText(slide,fmtPp(r.share_delta),6.38,yy,.70,.25,{fs:5.8,bold:true,color:C.red,align:'right'});addText(slide,fmtMoneyK(r.captured),7.30,yy,1.10,.25,{fs:5.8,bold:true,align:'right'});addText(slide,fmtNum(r.orders),8.82,yy,.55,.25,{fs:5.8,bold:true,align:'right'});addText(slide,fmtMoney(r.ticket),9.70,yy,.82,.25,{fs:5.6,bold:true,align:'right'});addText(slide,fmtPct(r.dispersion,1),10.85,yy,1.05,.25,{fs:5.6,bold:true,align:'right'})});addText(slide,'A priorização considera as maiores retrações de Share da semana frente à semana anterior.',.62,6.25,8.8,.20,{fs:7,bold:true});footer(slide)}
    {const slide=pptx.addSlide('RCH');header(slide,pptx,d.period==='week'?5:4,'DISPERSÕES','Mobilização do time | eStore CE+PI',lgG);card(slide,pptx,.55,1.0,3.7,1.42,'Dispersão Regional',fmtPct(s.dispersion,1),fmtNum(s.zeros)+' colaboradores sem venda',C.orange,C.wine);card(slide,pptx,4.52,1.0,3.7,1.42,'Time com venda',fmtPct(s.total?(s.total-s.zeros)/s.total:0,1),fmtNum(Math.max(0,s.total-s.zeros))+' colaboradores',C.green,C.up);card(slide,pptx,8.50,1.0,3.7,1.42,'Base Regional',fmtNum(s.total),'colaboradores considerados no período',C.sage,C.sage);addText(slide,'Lojas com maior dispersão',.62,2.85,4,.25,{fs:12,bold:true});barRows(slide,pptx,d.dispersion,.62,3.25,7.35,2.75,'disp',r=>r.st+' • '+supStore(r.st,r.name),C.orange);shape(slide,pptx,'roundRect',{x:8.55,y:3.02,w:3.75,h:2.75,fill:{color:'FFF8EA'},line:{color:'E9D7AE',width:.8}});addText(slide,'LEITURA',8.82,3.30,1.3,.18,{fs:7,bold:true,color:C.orange});addText(slide,'Dispersão mede a parcela do time ativo sem venda no período. O objetivo é ampliar participação com venda e reduzir concentração do resultado.',8.82,3.72,3.15,1.25,{fs:12,bold:true});footer(slide)}
    {const slide=pptx.addSlide('RCH');header(slide,pptx,d.period==='week'?6:5,'RECONHECIMENTO • COLABORADORES','Destaques da Regional | eStore CE+PI',lgG);podium(slide,pptx,d.collabCaptured.slice(0,3),'Top 3 • Volume Captado',r=>fmtMoneyK(r.c),.55,1.04,5.95,2.80,'collab');podium(slide,pptx,d.collabOrders.slice(0,3),'Top 3 • Volume de Pedidos',r=>fmtNum(r.o)+' pedidos',6.83,1.04,5.95,2.80,'collab');rankTable(slide,pptx,'4º ao 10º • Captado',d.collabCaptured.slice(3,10),.55,4.08,6.05,2.52,'collab',4);rankTable(slide,pptx,'4º ao 10º • Pedidos',d.collabOrders.slice(3,10),6.75,4.08,6.05,2.52,'collab',4);footer(slide)}
    {const slide=pptx.addSlide('RCH');header(slide,pptx,d.period==='week'?7:6,'PÓDIO REGIONAL DE SUPERVISORES','Ranking por volume captado da loja | eStore CE+PI',lgG);podium(slide,pptx,d.supervisorRanking.slice(0,3),'Top 3 • Lojas da Regional',r=>fmtMoneyK(r.c),1.10,1.02,11.0,3.15,'sup');rankTable(slide,pptx,'4º ao 10º • Supervisores (por volume da loja)',d.supervisorRanking.slice(3,10),1.05,4.25,11.25,2.20,'sup',4);addText(slide,'Quando a loja possui mais de um supervisor elegível, todos aparecem na mesma colocação com o primeiro nome de cada um.',1.08,6.62,10.9,.18,{fs:6.3,color:C.muted,align:'center'});footer(slide)}
    {const slide=pptx.addSlide('RCH');header(slide,pptx,d.period==='week'?8:7,'DIRECIONAMENTO FINAL','Esquadrão do Cliente | eStore CE+PI',lgG);addText(slide,'Com foco, disciplina e time engajado,\nseguimos evoluindo o eStore na CE+PI.',.62,1.45,5.3,1.10,{fs:23,bold:true});shape(slide,pptx,'line',{x:.63,y:3.02,w:.48,h:0,line:{color:C.orange,width:2}});addText(slide,'PERFORMANCE QUE VIRA AÇÃO',.63,3.25,3,.18,{fs:7.3,bold:true,color:C.orange});addText(slide,'Share • Venda Captada • Pedidos • Ticket • Dispersão • Reconhecimento',.63,3.60,5.3,.45,{fs:12,bold:true});const esq=await dataUrl('./esquadrao-cliente-card.jpg');if(esq)slide.addImage({data:esq,x:6.60,y:1.08,w:5.75,h:5.55});addText(slide,'MODA QUE INSPIRA O BRASIL',.63,6.58,3.5,.16,{fs:6.5,color:C.sage});}
    return pptx;
  }
  window.presGeneratePptxV99=async function(){try{status('Consolidando resultados e montando apresentação profissional...');const d=await loadData();const ppt=await buildDeck(d);const suf=d.period==='month'?(d.month||'mes'):d.period;status('Gerando PowerPoint...');await ppt.writeFile({fileName:'Panorama_Regional_eStore_CEPI_'+suf+'.pptx'});status('Apresentação gerada com sucesso.','success')}catch(e){console.error(e);status(e.message||'Não foi possível gerar a apresentação.','danger')}};
})();
